version: "3"

services:
  application:
    build: .
    image: unit_test_app
    container_name: unit_test_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true